
package com.nt.parsing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Book", targetNamespace = "http://parsing.nt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Book {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.nt.parsing.Book_Type
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBook", targetNamespace = "http://parsing.nt.com/", className = "com.nt.parsing.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://parsing.nt.com/", className = "com.nt.parsing.GetBookResponse")
    @Action(input = "http://parsing.nt.com/Book/getBookRequest", output = "http://parsing.nt.com/Book/getBookResponse")
    public Book_Type getBook(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
