
package com.nt.parsing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookDetailImplService", targetNamespace = "http://parsing.nt.com/", wsdlLocation = "http://localhost:3030/Proj4-BookApp-soap-contextLastApproch-ObjectBased/book?wsdl")
public class BookDetailImplService
    extends Service
{

    private final static URL BOOKDETAILIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKDETAILIMPLSERVICE_EXCEPTION;
    private final static QName BOOKDETAILIMPLSERVICE_QNAME = new QName("http://parsing.nt.com/", "BookDetailImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3030/Proj4-BookApp-soap-contextLastApproch-ObjectBased/book?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKDETAILIMPLSERVICE_WSDL_LOCATION = url;
        BOOKDETAILIMPLSERVICE_EXCEPTION = e;
    }

    public BookDetailImplService() {
        super(__getWsdlLocation(), BOOKDETAILIMPLSERVICE_QNAME);
    }

    public BookDetailImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKDETAILIMPLSERVICE_QNAME, features);
    }

    public BookDetailImplService(URL wsdlLocation) {
        super(wsdlLocation, BOOKDETAILIMPLSERVICE_QNAME);
    }

    public BookDetailImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKDETAILIMPLSERVICE_QNAME, features);
    }

    public BookDetailImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookDetailImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Book
     */
    @WebEndpoint(name = "BookDetailImplPort")
    public Book getBookDetailImplPort() {
        return super.getPort(new QName("http://parsing.nt.com/", "BookDetailImplPort"), Book.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Book
     */
    @WebEndpoint(name = "BookDetailImplPort")
    public Book getBookDetailImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://parsing.nt.com/", "BookDetailImplPort"), Book.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKDETAILIMPLSERVICE_EXCEPTION!= null) {
            throw BOOKDETAILIMPLSERVICE_EXCEPTION;
        }
        return BOOKDETAILIMPLSERVICE_WSDL_LOCATION;
    }

}
